# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: uds-minio

identityOpenidClientSecret: "replaceme"
identityOpenidConfigUrl:

domain: ###ZARF_VAR_DOMAIN###

rootPassword:
rootUser: minio

console:
  gateway: admin

# sso disabled until we can define the protocol mappers via sso secret
# or update the uds-core keycloak image
sso:
  enabled: false

apps: []
  # - name: test-app
  #   namespace: ""
  #   remoteSelector:
  #     app: minio
  #   bucketNames:
  #     - test-bucket
  #     - test-bucket-2
  #     - test-bucket-3
  #   policy: ""
  #   user: minio
  #   copyPassword:
  #     enabled: true
  #     secretName:
  #     secretIDKey:
  #     secretPasswordKey:

mcImage: ""
mcShell: ""
ambient: true

# Custom UDS network rules for the built-in tenant Package.
additionalNetworkAllow: []

# Custom UDS network rules for the operator Package.
operatorAdditionalNetworkAllow: []
