# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: uds-minio

identityOpenidClientSecret: "replaceme"
identityOpenidConfigUrl:

domain: ###ZARF_VAR_DOMAIN###

rootPassword:
rootUser: minio

console:
  gateway: admin

# sso disabled until we can define the protocol mappers via sso secret
# or update the uds-core keycloak image
sso:
  enabled: false

apps: []
  # - name: test-app
  #   namespace: ""
  #   remoteSelector:
  #     app: minio
  #   bucketNames:
  #     - test-bucket
  #     - test-bucket-2
  #     - test-bucket-3
  #   policy: ""
  #   user: minio
  #   serviceAccounts:
  #     - name: minio-test-bucket-sa
  #       policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"s3:PutObject\",\"s3:AbortMultipartUpload\"],\"Resource\":[\"arn:aws:s3:::test-bucket/*\"]},{\"Effect\":\"Allow\",\"Action\":[\"s3:ListBucket\"],\"Resource\":[\"arn:aws:s3:::test-bucket\"]}]}"
  #       user: minio
  #     - name: minio-test-bucket-2-sa
  #       policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"s3:PutObject\",\"s3:AbortMultipartUpload\"],\"Resource\":[\"arn:aws:s3:::test-bucket-2/*\"]},{\"Effect\":\"Allow\",\"Action\":[\"s3:ListBucket\"],\"Resource\":[\"arn:aws:s3:::test-bucket-2\"]}]}"
  #       user: minio
  #       accessKey: "minio-test-bucket-2-sa"
  #       secretkey: "SuperSecret123@"
  #   copyPassword:
  #     enabled: true
  #     secretName:
  #     secretIDKey:
  #     secretPasswordKey:

mcImage: ""
mcShell: ""
ambient: true

# Custom UDS network rules for the built-in tenant Package.
additionalNetworkAllow: []

# Custom UDS network rules for the operator Package.
operatorAdditionalNetworkAllow: []
