# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tenant:
  image:
    repository: cgr.dev/defenseunicorns.com/minio
    # renovate: datasource=docker depName=cgr.dev/defenseunicorns.com/minio versioning=regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
    tag: v0.20260520.234452
    pullPolicy: IfNotPresent
