# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# renovate: datasource=docker depName=cgr.dev/defenseunicorns.com/minio-client versioning=regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
mcImage: cgr.dev/defenseunicorns.com/minio-client:0.20250813.083541
mcShell: /bin/bash
