# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

operator:
  image:
    repository: cgr.dev/defenseunicorns.com/minio-operator
    tag: 7.1.1
  sidecarImage:
    repository: cgr.dev/defenseunicorns.com/minio-operator-sidecar
    tag: 7.1.1
    pullPolicy: IfNotPresent
