# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tenant:
  image:
    repository: ghcr.io/uds-packages/minio-operator/container/chainguard/minio
    # renovate: datasource=docker depName=ghcr.io/uds-packages/minio-operator/container/chainguard/minio versioning=semver
    tag: 0.20260410.215259-r1
